---
  - name: Play3
    hosts: virtualmachines
    become: yes
    become_user: root
    tasks:
      - name: Copy file with owner and permissions
        ansible.builtin.copy:
          src: /Users/sanjana.thamke/.ssh/gcp_prod
          dest:  /home/ubuntu/
          mode: '0777'
              
        

